baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "minimal-theme"
sectionPagesMenu = "main"
[params]
  githubRepo = 'https://github.com/about-hugo/minimal-site'
  githubEditPath = "edit/main/"
  themeRepo = 'https://github.com/about-hugo/minimal-site'
  themePartialPath = 'tree/main/themes/minimal-theme/layouts'

[menus]
  [[menus.main]]
    name = 'HOME'
    pageRef = '/'
    weight = 100
  [[menus.main]]
    name = 'Added by config in hugo.toml'
    title = 'page title set in config'
    pageRef = '/subdir1/part2/content'
    weight = 1000


  [[menus.myownmenu]]
    name = 'Home'
    pageRef = '/'
    weight = 1
  [[menus.myownmenu]]
    name = 'posts'
    pageRef = '/posts'
    weight = 2

   