baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "minimal-theme"
sectionPagesMenu = "main"
[params]
  githubRepo = 'https://github.com/about-hugo/minimal-site'
  githubEditPath = "edit/main/"
  themeRepo = 'https://github.com/about-hugo/minimal-site'
  themePartialPath = 'tree/main/themes/minimal-theme/layouts'

[menus]
  [[menus.main]]
    name = 'Added by config in hugo.toml'
    pageRef = '/subdir1/part2/content'
    weight = 1