baseURL = '/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "minimal-theme"
sectionPagesMenu = "main"
[params]
  githubRepo = 'https://github.com/bkleinen/minimal-site'
  githubEditPath = "edit/main/"